steps:
  - name: build-and-deploy
    image: docker:dind
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker build -t $DOCKER_USERNAME/react-app:latest .
      - docker stop react-app || true
      - docker rm react-app || true
      - docker run -d --rm --name react-app -p 3000:3000 $DOCKER_USERNAME/react-app:latest

  - name: lighthouse-audit
    image: zenika/alpine-chrome:with-node
    user: root
    environment:
      HOME: /tmp
    commands:
      - mkdir -p $HOME
      - npm config set cache $HOME/.npm
      - npm install lighthouse
      - npx lighthouse http://localhost:3000 --output html --output-path ./report.html
