---
steps:
  - name: build-and-deploy
    image: docker:24
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - docker info
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker build -t "$DOCKER_USERNAME/react-app:latest" .
      - docker run -d --rm --name react-app -p 3000:3000 "$DOCKER_USERNAME/react-app:latest"
      - sleep 10

  - name: lighthouse
    image: patrickhulce/lhci-client
    commands:
      - lhci autorun --config=/app/.lighthouserc.json
    volumes:
      - .:/app

  - name: cleanup
    image: docker:24
    commands:
      - docker stop react-app || true
      - docker rm react-app || true
      - docker run -d --rm --name react-app -p 3000:3000 "$DOCKER_USERNAME/react-app:latest"