---
steps:
  - name: build-and-deploy
    image: docker:24-dind
    privileged: true
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker build -t "$DOCKER_USERNAME/react-app:latest" .
      - docker run -d --rm --name react-app -p 3000:3000 "$DOCKER_USERNAME/react-app:latest"
      - sleep 10

  - name: lighthouse
    image: patrickhulce/lhci-client
    commands:
      - lhci autorun --upload.target=temporary-public-storage --collect.url=http://localhost:3000

  - name: cleanup
    image: docker:24
    commands:
      - docker stop react-app || true
      - docker rm react-app || true

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
