# .woodpecker.yml

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

steps:
  build-and-deploy:
    image: docker
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - set -ex
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker build -t $DOCKER_USERNAME/react-app:$CI_COMMIT_SHORT_SHA .
      - docker stop react-app || true
      - docker rm react-app || true
      - docker run -d --rm --name react-app -p 3000:3000 $DOCKER_USERNAME/react-app:$CI_COMMIT_SHORT_SHA
