steps:
  build-and-deploy:
    image: docker
    privileged: true
    when:
      event:
        - push
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker build -t $DOCKER_USERNAME/react-app:$CI_COMMIT_SHORT_SHA .
      - docker stop react-app || true
      - docker rm react-app || true
      - docker run -d --rm --name react-app -p 3000:3000 $DOCKER_USERNAME/react-app:$CI_COMMIT_SHORT_SHA
      