# ---
# steps:
#   - name: build-and-deploy
#     image: docker:24
#     privileged: true
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#     environment:
#       DOCKER_USERNAME:
#         from_secret: DOCKER_USERNAME
#       DOCKER_PASSWORD:
#         from_secret: DOCKER_PASSWORD
#     commands:
#       - docker info
#       - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
#       - docker stop react-app || true
#       - docker rm react-app || true
#       - docker build -t "$DOCKER_USERNAME/react-app:latest" .
#       - docker run -d --rm --name react-app -p 3000:3000 "$DOCKER_USERNAME/react-app:latest"
#       - sleep 10

#   - name: lighthouse
#     image: patrickhulce/lhci-client
#     volumes:
#       - name: workspace
#         path: /app
#     commands:
#       - lhci autorun --config=/app/.lighthouserc.json

#   - name: cleanup
#     image: docker:24
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#     commands:
#       - docker stop react-app || true
#       - docker rm react-app || true

# volumes:
#   - name: workspace
#     host:
#       path: ${WOODPECKER_WORKSPACE}  # dynamically points to the repo checkout




---
steps:
  - name: build-and-test
    image: node:20
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
      LHCI_CHROME_FLAGS: "--no-sandbox"
    commands:
      - apt-get update && apt-get install -y docker.io chromium
      - docker info
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker stop react-app || true
      - docker rm react-app || true
      - docker build -t "$DOCKER_USERNAME/react-app:latest" .
      - docker run -d --name react-app -p 3001:3000 "$DOCKER_USERNAME/react-app:latest"
      - sleep 10
      - npm install -g @lhci/cli
      - LHCI_CHROME_PATH=$(which chromium) lhci autorun --url=http://localhost:3001 --config=.lighthouserc.json
      - docker stop react-app || true
      - docker rm react-app || true




