steps:
  - name: build-and-deploy
    image: docker:dind
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker build -t $DOCKER_USERNAME/react-app:latest .
      - docker stop react-app || true
      - docker rm react-app || true
      - docker run -d --rm --name react-app -p 3000:3000 $DOCKER_USERNAME/react-app:latest

  - name: lighthouse-audit
    image: cypress/browsers:node18.12.0-chrome107
    user: node
    environment:
      CHROME_PATH: "/Applications/Google\ Chrome.app/Contents/MacOS/Google Chrome"
      HOME: /usr/local/bin/node
    commands:
      - lighthouse http://localhost:3000 \
       --chrome-path="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" \
       --output html \
       --output-path ./report.html